import { Experience } from '@/types/PagePreview';
import { Resume } from './resume';

const Preview: React.FC = () => {
    return (<Resume {...warp} />)
};

export const warp = {
    id: 'warp',
    name: 'Warp',
    title: 'Senior Software Engineer',

    startDate: new Date('2024-09-30'),
    endDate: null, // Still work here

    description: <div className='space-y-4'>
    <div>
    Rust, TypeScript, React, Golang.
    </div>
    <div>
    - Developed <a href='https://docs.warp.dev/terminal/warpify/ssh' >TMUX-based SSH Warpification</a> support enabling AI features in remote sessions
    <br />
    - Built self-serve Admin Panel by productionizing 20+ enterprise settings in just under 6 weeks
    <br />
    - Modernized tech stack with autogenerated GraphQL types, Tailwind, and Vite migrations
    <br />
    - Built VSCode Extension that enabled strategic unlock: Warp in VSCode for internal hackathon
    <br />
    - Mentored 4 junior engineers, hosted 1 intern
    </div>
    <div>
        <a href="https://www.warp.dev/" target='_blank'>
            warp.dev
        </a>
    </div>
    </div>,

    heroImageSrc: undefined,
    iconSrc: '/warp.png',
    preview: <Preview />,
    href: '/experience#warp'
} satisfies Experience;
